// Backfill `Mandal.name` with Telugu names. The original seed (seed-locations.ts)
// set both `name` and `nameEn` to the English string, so every mandal row
// renders in English. This script restores Telugu by mapping each English
// mandal name to its standard Telugu form (sourced from AP gov mandal lists +
// Wikipedia Telugu articles).
//
// Idempotent — re-running just re-applies the same mapping.
//
// Run:  cd packages/db && bunx tsx scripts/backfill-mandal-telugu.ts

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Telugu mappings for every distinct English mandal name in the DB.
// Telugu spellings checked against AP gov district pages + Wikipedia te.wiki.
const TE: Record<string, string> = {
  "Adoni": "ఆదోని",
  "Agali": "అగళి",
  "Allagadda": "ఆళ్లగడ్డ",
  "Alur": "అలూరు",
  "Amarapuram": "అమరాపురం",
  "Anantapur": "అనంతపురం",
  "Anantapur Rural": "అనంతపురం రూరల్",
  "Aspari": "అస్పరి",
  "Atlur": "ఆత్లూరు",
  "Atmakur": "ఆత్మకూరు",
  "B Kodur": "బి. కోడూరు",
  "B Kothakota": "బి. కొత్తకోట",
  "Badvel": "బద్వేలు",
  "Baireddipalle": "బైరెడ్డిపల్లె",
  "Balayapalli": "బాలయపల్లి",
  "Banaganapalle": "బనగానపల్లె",
  "Bandi Atmakur": "బండి ఆత్మకూరు",
  "Bangarupalem": "బంగారుపాళెం",
  "Bathalapalle": "బత్తలపల్లె",
  "Beluguppa": "బెళుగుప్ప",
  "Bethamcherla": "బేతంచర్ల",
  "Bommanahal": "బొమ్మనహాల్",
  "Brahmamgarimattam": "బ్రహ్మంగారిమట్టం",
  "Brahmasamudram": "బ్రహ్మసముద్రం",
  "Bukkapatnam": "బుక్కపట్నం",
  "Bukkarayasamudram": "బుక్కరాయసముద్రం",
  "C Belagal": "సి. బెళగల్",
  "C K Palli": "సి.కె. పల్లి",
  "Chagalamarri": "చాగలమర్రి",
  "Chakrayapet": "చక్రాయపేట",
  "Chandragiri": "చంద్రగిరి",
  "Chapadu": "చాపాడు",
  "Chilamathur": "చిలమత్తూరు",
  "Chillakur": "చిల్లకూరు",
  "Chinnagottigallu": "చిన్నగొట్టిగల్లు",
  "Chinnamandyam": "చిన్నమండ్యం",
  "Chinthakommadinne": "చింతకొమ్మదిన్నె",
  "Chippagiri": "చిప్పగిరి",
  "Chittamur": "చిట్టమూరు",
  "Chittoor": "చిత్తూరు",
  "Chitvel": "చిట్వేలు",
  "Chowdepalle": "చౌడేపల్లె",
  "D Hirehal": "డి. హిరేహాల్",
  "Dakkili": "ఢక్కిలి",
  "Devanakonda": "దేవనకొండ",
  "Dharmavaram": "ధర్మవరం",
  "Dhone": "డోను",
  "Doravarisatram": "దోరవారిసత్రం",
  "Dornipadu": "దోర్నిపాడు",
  "Duvvuru": "దువ్వూరు",
  "G D Nellore": "జి.డి. నెల్లూరు",
  "Gadivemula": "గాడివేముల",
  "Galiveedu": "గాలివీడు",
  "Gandlapenta": "గండ్లపెంట",
  "Gangavaram": "గంగవరం",
  "Garladinne": "గార్లదిన్నె",
  "Gonegandla": "గోనెగండ్ల",
  "Gooty": "గుత్తి",
  "Gopavaram": "గోపవరం",
  "Gorantla": "గోరంట్ల",
  "Gospadu": "గోస్పాడు",
  "Gudibanda": "గుడిబండ",
  "Gudipala": "గుడిపాల",
  "Gudipalle": "గుడిపల్లె",
  "Gudur": "గూడూరు",
  "Gummagatta": "గుమ్మగట్ట",
  "Guntakal": "గుంతకల్",
  "Gurramkonda": "గుర్రంకొండ",
  "Halaharvi": "హాలహర్వి",
  "Hindupur": "హిందూపురం",
  "Holagunda": "హోళగుంద",
  "Irala": "ఇరాల",
  "Jammalamadugu": "జమ్మలమడుగు",
  "Jupadu Bungalow": "జూపాడు బంగ్లా",
  "K V B Puram": "కె.వి.బి. పురం",
  "Kadapa": "కడప",
  "Kadiri": "కదిరి",
  "Kalakada": "కలకడ",
  "Kalasapadu": "కలసపాడు",
  "Kalikiri": "కలికిరి",
  "Kallur": "కల్లూరు",
  "Kaluvoya": "కలువోయ",
  "Kalyandurg": "కళ్యాణదుర్గం",
  "Kamalapuram": "కమలాపురం",
  "Kambadur": "కంబదూరు",
  "Kambhamvaripalle": "కంభంవారిపల్లె",
  "Kanaganapalli": "కనగానపల్లె",
  "Kanekal": "కనేకల్లు",
  "Karvetinagar": "కార్వేటినగరం",
  "Khajipet": "ఖాజీపేట",
  "Kodumur": "కోడుమూరు",
  "Kodur": "కోడూరు",
  "Koilkuntla": "కోయిలకుంట్ల",
  "Kolimigundla": "కొలిమిగుండ్ల",
  "Kondapuram": "కొండాపురం",
  "Kosigi": "కోసిగి",
  "Kota": "కోట",
  "Kothacheruvu": "కొత్తచెరువు",
  "Kothapalle": "కొత్తపల్లె",
  "Kowthalam": "కౌతాళం",
  "Krishnagiri": "కృష్ణగిరి",
  "Kudair": "కుదైర్",
  "Kundurpi": "కుందుర్పి",
  "Kuppam": "కుప్పం",
  "Kurabalakota": "కురబలకోట",
  "Kurnool": "కర్నూలు",
  "Lakkireddipalle": "లక్కిరెడ్డిపల్లె",
  "Lakkireddipalli": "లక్కిరెడ్డిపల్లి",
  "Lepakshi": "లేపాక్షి",
  "Lingala": "లింగాల",
  "Madakasira": "మడకశిర",
  "Madanapalle": "మదనపల్లె",
  "Maddikera": "మద్దికెర",
  "Mahanandi": "మహానంది",
  "Mantralayam": "మంత్రాలయం",
  "Midthur": "మిడుతూరు",
  "Muddanur": "ముద్దనూరు",
  "Mudigubba": "ముదిగుబ్బ",
  "Mulakalacheruvu": "ములకలచెరువు",
  "Mydukur": "మైదుకూరు",
  "Mylavaram": "మైలవరం",
  "Nagalapuram": "నాగలాపురం",
  "Nagari": "నగరి",
  "Naidupeta": "నాయుడుపేట",
  "Nallacheruvu": "నల్లచెరువు",
  "Nallamada": "నల్లమడ",
  "Nambulapulakunta": "నంబులపూలకుంట",
  "Nandalur": "నందలూరు",
  "Nandavaram": "నందవరం",
  "Nandikotkur": "నందికొట్కూరు",
  "Nandyal": "నంద్యాల",
  "Narayanavanam": "నారాయణవనం",
  "Narpala": "నార్పల",
  "Nimmanapalle": "నిమ్మనపల్లె",
  "Obuladevaracheruvu": "ఓబులదేవరచెరువు",
  "Obulavaripalli": "ఓబులవారిపల్లి",
  "Orvakal": "ఓర్వకల్",
  "Owk": "ఔక్",
  "Ozili": "ఓజిలి",
  "Pagidyala": "పగడ్యాల",
  "Pakala": "పాకాల",
  "Palamaner": "పలమనేరు",
  "Palasamudram": "పాలసముద్రం",
  "Pamidi": "పామిడి",
  "Pamulapadu": "పాములపాడు",
  "Panyam": "పాణ్యం",
  "Parigi": "పరిగి",
  "Pattikonda": "పత్తికొండ",
  "Peapally": "పీపల్లి",
  "Pedda Panjani": "పెద్ద పంజాణి",
  "Peddakadubur": "పెద్దకడుబూరు",
  "Peddamandyam": "పెద్దమండ్యం",
  "Peddamudiyam": "పెద్దముడియం",
  "Peddapappur": "పెద్దపప్పూరు",
  "Peddathippasamudram": "పెద్దతిప్పసముద్రం",
  "Peddavadugur": "పెద్దవడుగూరు",
  "Pellakur": "పెల్లకూరు",
  "Penagalur": "పెనగలూరు",
  "Pendlimarri": "పెండ్లిమర్రి",
  "Penukonda": "పెనుకొండ",
  "Penumuru": "పెనుమూరు",
  "Pichatur": "పిచ్చాటూరు",
  "Pileru": "పీలేరు",
  "Porumamilla": "పోరుమామిళ్ల",
  "Proddatur": "ప్రొద్దుటూరు",
  "Pulicherla": "పులిచెర్ల",
  "Pulivendla": "పులివెందుల",
  "Pullampeta": "పుల్లంపేట",
  "Punganur": "పుంగనూరు",
  "Puthalapattu": "పూతలపట్టు",
  "Putluru": "పుట్లూరు",
  "Puttaparthi": "పుట్టపర్తి",
  "Puttur": "పుత్తూరు",
  "Rajampet": "రాజంపేట",
  "Rajupalem": "రాజుపాళెం",
  "Ramachandrapuram": "రామచంద్రాపురం",
  "Ramagiri": "రామగిరి",
  "Ramakuppam": "రామకుప్పం",
  "Ramapuram": "రామాపురం",
  "Ramasamudram": "రామసముద్రం",
  "Raptadu": "రాప్తాడు",
  "Rapur": "రాపూరు",
  "Rayachoti": "రాయచోటి",
  "Rayadurg": "రాయదుర్గం",
  "Renigunta": "రేణిగుంట",
  "Roddam": "రొద్దం",
  "Rolla": "రోళ్ళ",
  "Rompicherla": "రొంపిచెర్ల",
  "Rudravaram": "రుద్రవరం",
  "S R Puram": "ఎస్.ఆర్. పురం",
  "Sambepalli": "సంబేపల్లి",
  "Sanjamala": "సంజామల",
  "Santhipuram": "శాంతిపురం",
  "Satyavedu": "సత్యవేడు",
  "Settur": "సెట్టూరు",
  "Sidhout": "సిద్దవటం",
  "Simhadripuram": "సింహాద్రిపురం",
  "Singanamala": "శింగనమల",
  "Sirvel": "సిర్వెల్",
  "Sodam": "సొదం",
  "Somala": "సోమల",
  "Somandepalle": "సోమందేపల్లి",
  "Sri Avadhutha Kasinayana": "శ్రీ అవధూత కాశీనాయన",
  "Srikalahasti": "శ్రీకాళహస్తి",
  "Srisailam": "శ్రీశైలం",
  "Sullurpeta": "సూళ్ళూరుపేట",
  "Sydapuram": "సైదాపురం",
  "Tada": "తడ",
  "Tadimarri": "తాడిమర్రి",
  "Tadpatri": "తాడిపత్రి",
  "Talupula": "తలుపుల",
  "Tanakal": "తనకల్",
  "Thamballapalle": "తంబళ్ళపల్లి",
  "Thavanampalle": "తవణంపల్లె",
  "Thondur": "తొండూరు",
  "Thottambedu": "తొట్టంబేడు",
  "Tirupati Rural": "తిరుపతి రూరల్",
  "Tirupati Urban": "తిరుపతి అర్బన్",
  "Tuggali": "తుగ్గలి",
  "Uravakonda": "ఉరవకొండ",
  "Uyyalawada": "ఉయ్యాలవాడ",
  "V Kota": "వి. కోట",
  "Vadamalapeta": "వడమాలపేట",
  "Vajrakarur": "వజ్రకరూరు",
  "Vakadu": "వాకాడు",
  "Vallur": "వల్లూరు",
  "Valmikipuram": "వాల్మీకిపురం",
  "Varadaiahpalem": "వరదయ్యపాళెం",
  "Vedurukuppam": "వేదురుకుప్పం",
  "Veeraballi": "వీరబల్లి",
  "Veerapunayunipalle": "వీరపునయునిపల్లె",
  "Veldurthi": "వెల్దుర్తి",
  "Velgode": "వెల్గోడు",
  "Vempalle": "వేంపల్లె",
  "Vemula": "వేముల",
  "Venkatagiri": "వెంకటగిరి",
  "Vidapanakal": "విదపనకల్",
  "Vijayapuram": "విజయపురం",
  "Vontimitta": "వొంటిమిట్ట",
  "Yadamarri": "యాదమర్రి",
  "Yadiki": "యాడికి",
  "Yellanur": "ఎల్లనూరు",
  "Yemmiganur": "ఎమ్మిగనూరు",
  "Yerpedu": "ఏర్పేడు",
  "Yerraguntla": "యెర్రగుంట్ల",
  "Yerravaripalem": "ఎర్రవారిపాలెం",
};

async function main() {
  const all = await prisma.mandal.findMany({ select: { id: true, name: true, nameEn: true } });
  console.log(`Found ${all.length} mandal rows.`);

  // Some rows may already have Telugu in `name` (re-runs). For safety, key off `nameEn`.
  const missing = new Set<string>();
  let updated = 0, skipped = 0;

  for (const m of all) {
    const en = m.nameEn;
    const te = TE[en];
    if (!te) {
      missing.add(en);
      continue;
    }
    if (m.name === te) {
      skipped++;
      continue;
    }
    await prisma.mandal.update({ where: { id: m.id }, data: { name: te } });
    updated++;
  }

  console.log(`Updated: ${updated}, already-Telugu: ${skipped}`);
  if (missing.size > 0) {
    console.warn(`Missing Telugu mapping for ${missing.size} mandal names — add them to TE{}:`);
    for (const n of [...missing].sort()) console.warn(`  "${n}": "???",`);
  }
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
