import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@rayalaseema/db";

// Public rashi-phalalu feed. Reads the latest DAILY + WEEKLY rows generated by
// the admin cron (apps/admin/src/app/api/cron/horoscope) - NO live third-party
// fetch or API keys on the request path (the old Prokerala/Azure inline code +
// hardcoded secrets were removed). Fast, key-less, survives deploys.

const rashis = [
  { id: "mesha", name: "మేషం", nameEn: "Aries", symbol: "♈", dates: "మార్చి 21 - ఏప్రిల్ 19" },
  { id: "vrushabha", name: "వృషభం", nameEn: "Taurus", symbol: "♉", dates: "ఏప్రిల్ 20 - మే 20" },
  { id: "mithuna", name: "మిథునం", nameEn: "Gemini", symbol: "♊", dates: "మే 21 - జూన్ 20" },
  { id: "karkataka", name: "కర్కాటకం", nameEn: "Cancer", symbol: "♋", dates: "జూన్ 21 - జులై 22" },
  { id: "simha", name: "సింహం", nameEn: "Leo", symbol: "♌", dates: "జులై 23 - ఆగస్టు 22" },
  { id: "kanya", name: "కన్య", nameEn: "Virgo", symbol: "♍", dates: "ఆగస్టు 23 - సెప్టెంబర్ 22" },
  { id: "tula", name: "తులా", nameEn: "Libra", symbol: "♎", dates: "సెప్టెంబర్ 23 - అక్టోబర్ 22" },
  { id: "vrushchika", name: "వృశ్చికం", nameEn: "Scorpio", symbol: "♏", dates: "అక్టోబర్ 23 - నవంబర్ 21" },
  { id: "dhanu", name: "ధనుస్సు", nameEn: "Sagittarius", symbol: "♐", dates: "నవంబర్ 22 - డిసెంబర్ 21" },
  { id: "makara", name: "మకరం", nameEn: "Capricorn", symbol: "♑", dates: "డిసెంబర్ 22 - జనవరి 19" },
  { id: "kumbha", name: "కుంభం", nameEn: "Aquarius", symbol: "♒", dates: "జనవరి 20 - ఫిబ్రవరి 18" },
  { id: "meena", name: "మీనం", nameEn: "Pisces", symbol: "♓", dates: "ఫిబ్రవరి 19 - మార్చి 20" },
];

export async function GET(req: NextRequest) {
  const rashiParam = req.nextUrl.searchParams.get("rashi");

  // Newest row per (rashi, period). One query, dedupe in memory.
  const rows = await prisma.horoscope.findMany({
    orderBy: { date: "desc" },
    take: 400,
    select: { rashi: true, period: true, predictionTe: true, date: true },
  });

  const daily = new Map<string, string>();
  const weekly = new Map<string, string>();
  for (const r of rows) {
    if (r.period === "DAILY" && !daily.has(r.rashi)) {
      daily.set(r.rashi, r.predictionTe);
    } else if (r.period === "WEEKLY" && !weekly.has(r.rashi)) {
      weekly.set(r.rashi, r.predictionTe);
    }
  }

  const results = rashis.map((r) => ({
    ...r,
    prediction: daily.get(r.id) || "",
    weeklyPrediction: weekly.get(r.id) || "",
  }));

  if (rashiParam) {
    return NextResponse.json(results.find((r) => r.id === rashiParam) || null);
  }

  // Always label with TODAY's date (IST) - this is "నేటి రాశి ఫలాలు", so the
  // header must track the calendar day, not the date the rows were generated.
  const dateLabel = new Date().toLocaleDateString("te-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "Asia/Kolkata",
  });

  return NextResponse.json(
    { rashis: results, date: dateLabel, source: "రాయలసీమ న్యూస్ జ్యోతిష్యం" },
    { headers: { "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400" } },
  );
}
